### ISSUE TITLE
Program cannot reach the number ({}) of genomes required for core-genome SNP calling

### ISSUE THREAD

**Issue by snayfach** [zjshi/CallM#2] opened 2021-11-22 20:06 UTC
Hi Jason - I tried running the code using a set of 67 E. coli genomes, but got the following error:

> b''[clustering] start
> [clustering] done
> [clustering] 66 genomes have been included in clusters
> [Searching lower cap]
> [clustering] start
> [clustering] done
> [clustering] 38 genomes have been included in clusters
> 	0.002: 38 tag genomes
> [clustering] start
> [clustering] done
> [clustering] 15 genomes have been included in clusters
> 	0.0002: 56 tag genomes
> [clustering] start
> [clustering] done
> [clustering] 9 genomes have been included in clusters
> 	2e-05: 59 tag genomes
> [End earching]
> [Searching optimal d-cut]
> Program cannot reach the number ({}) of genomes required for core-genome SNP calling.
> Proceeding with orginal set of genomes
> [Searching optimal d-cut]
> Program cannot reach the number ({}) of genomes required for core-genome SNP calling.
> Proceeding with orginal set of genomes. Or try higher MAF
> Traceback (most recent call last):
>   File "/global/cscratch1/sd/snayfach/tools/CallM/bin/CallM", line 1229, in <module>
>     main()
>   File "/global/cscratch1/sd/snayfach/tools/CallM/bin/CallM", line 1220, in main
>     call_snps_main(args)
>   File "/global/cscratch1/sd/snayfach/tools/CallM/bin/CallM", line 1072, in call_snps_main
>     id_clusters(args)
>   File "/global/cscratch1/sd/snayfach/tools/CallM/bin/CallM", line 569, in id_clusters
>     for cluster in optimal_clusters:
> TypeError: 'NoneType' object is not iterable

**Comment by wjj666** [comment] 2022-01-02 04:13
Hi, @snayfach, I have the same problem with CallM. Have you solved this problem? If solved, could you please help me? Thank you.

**Comment by zjshi** [comment] 2022-01-04 01:36
Hi Stephen, the problem is seemingly due to fewer genomes supplied than what is required for SNP calling with a MAF of 1%. It should be fixed now as CallM is patched to automatically include all genomes in such cases. Thanks for reporting this issue!

**Closed as completed by zjshi** 2022-01-04 01:36 UTC
